[5ronaminC] wishlist_DB에 DATA INSERT 기능 구현
wecode-bootcamp-korea/48-2nd-5ronaminC-backend pull request #6
Opened 2023-08-24 07:47 UTC by ghj1

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- user가 마음에 드는 제품을 wishlists에 저장
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
-  wishlists DB TBALE에 DATA INSERT하는 기능 구현

<br />

## :: 테스트 결과 이미지
- wishlists table
<img width="230" alt="스크린샷 2023-08-24 16 46 31" src="https://github.com/wecode-bootcamp-korea/48-2nd-5ronaminC-backend/assets/90584168/bd63018b-c637-491e-810e-34e6b19d54fc">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-08-24 08:01 UTC, kyeongraekim requested changes

2023-08-24 08:01 UTC, kyeongraekim commented on api/controllers/wishController.js
> +    const userId = req.body.user_id;
- user_id는 node.js 와 자바스크립트 코드 기준 잘못된 네이밍 컨벤션입니다.

2023-08-24 08:01 UTC, kyeongraekim commented on api/controllers/wishController.js
> +    res.status(201).json({ insertId });
- insertId 외에 좋아요 가 성공했음을 암시하는 성공 메세지를 보내주세요.
- 해당 insertId는 프론트엔드와 클라이언트에서의 활용도가 매우 낮아 보입니다.

2023-08-24 08:01 UTC, kyeongraekim commented on api/routes/wishRouter.js
> +// const { loginRequired } = require('../utils/auth');
- main으로의 푸시에는 꼭 불필요한 주석문을 모두 삭제한 후의 소스코드만 반영하여 진행합니다.

2023-08-24 11:43 UTC, ghj1 commented
모두 수정하여 재푸시 했습니다.

2023-08-25 01:32 UTC, kyeongraekim requested changes

2023-08-25 01:32 UTC, kyeongraekim commented on api/controllers/wishController.js
> +    const userId = req.body.userId;
- 해당내용은 인가코드가 들어왔음을 가정하고 작성해주시고, 만일 팀내 인가코드가 없어서 해당 API 구동 시험이 힘든경우에는 인가 코드에 대한 별도의 PR을 올려주셔서 빠른 머지로 진행하여주세요!~

2023-08-29 04:49 UTC, ghj1 commented
인가 추가하여 재푸시 합니다!

2023-08-29 05:16 UTC, kyeongraekim approved these changes

2023-08-29 05:16 UTC, merged